### PR TITLE
Toffy Pipeline Flowchart

### LINKED ISSUE #199: Create visual flowchart for toffy pipeline
**Is your feature request related to a problem? Please describe.**
There are a lot different pieces in the toffy processing, some of which are optional, some of which are required. It would be nice to have a visual representation of the dependencies between different notebooks to guide users.

**Describe the solution you'd like**
A diagram that shows each step, and what it depends on. 

For example: 
set up toffy notebook at the beginning. 
This branches into either the TMA notebook or the tiled image notebooks. 
These come back together, then branch into either 3a (watcher notebook) or 3b-3e (processing notebooks)
These branches come back together for rosetta processing (with optional side branch loop for rosetta finetuning). 
This leads to normalization
This leads to reorganizaiton

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #199.

**How did you implement your changes**

Added a flowchart via LucidChart.

**Remaining issues**

None ATM.

### CODE REVIEW

**Review by ngreenwald — CHANGES_REQUESTED** [review]
This looks quite nice. Two main comments. 
1. Right now the notebook names are a bit hard to read. Maybe deleting the .ipynb will buy some more space, and then making each shape slightly wider. 
2. I'd like to have this on a slide for the workshop. Is there a way to make it a bit more compact? Collapsing some of the transition-only shapes perhaps?

**Comment by srivarra** [comment]
**Transparent PNG**
toffy_processing-transparent

**Comment by ngreenwald** [comment]
Looks great!

1. Can you make the notebook names a different color or underlined or something to make it obvious that it's referring to the notebooks?
2. For the arrows that connect each column, can you make them snake from the bottom of the column to the top of the next, pointing directly to the next step, rather than left-to-right across the image?

**Comment by srivarra** [comment]
@ngreenwald

**Review by ngreenwald — APPROVED** [review]
Looks good!

**Pull request merged**
