### PR TITLE
Refresh intermediate callback plotting on each new FOV

### LINKED ISSUE #347: Potential memory leak in watcher
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
I ran into an out of memory error when attempting to run the watcher. 
This happened after 35 FOVs had already been processed, all of the same size. I don't believe there is anything unique about the FOV it failed on. 

This was on Drago. run_name: 2023-04-06T_hazing_1,  fov-35-scan-1

```
emoryError                               Traceback (most recent call last)
Cell In[7], line 1
----> 1 start_watcher(base_dir, log_path, fov_callback, run_callback, intermediate_callback)

File ~\Documents\toffy\scripts\..\toffy\fov_watcher.py:296, in start_watcher(run_folder, log_folder, fov_callback, run_callback, intermediate_callback, completion_check_time, zero_size_timeout)
    273 """ Passes bin files to provided callback functions as they're created
    274 
    275 Args:
   (...)
    293         number of seconds to wait for non-zero file size
    294 """
    295 observer = Observer()
--> 296 event_handler = FOV_EventHandler(run_folder, log_folder, fov_callback, run_callback,
    297                                  intermediate_callback, zero_size_timeout)
    298 observer.schedule(event_handler, run_folder, recursive=True)
    299 observer.start()

File ~\Documents\toffy\scripts\..\toffy\fov_watcher.py:195, in FOV_EventHandler.__init__(self, run_folder, log_folder, fov_callback, run_callback, intermediate_callback, timeout)
    193 for root, dirs, files in os.walk(run_folder):
    194     for name in files:
--> 195         self.on_created(FileCreatedEvent(os.path.join(root, name)))

File ~\Documents\toffy\scripts\..\toffy\fov_watcher.py:237, in FOV_EventHandler.on_created(self, event)
    231 # run per_fov callbacks
    232 logf.write(
    233     f'{datetime.now().strftime("%d/%m/%Y %H:%M:%S")} -- '
    234     f'Running {self.fov_func.__name__} on {point_name}\n'
    235 )
--> 237 self.fov_func(self.run_folder, point_name)
    238 self.run_structure.processed(point_name)
    240 if self.inter_func:

File ~\Documents\toffy\scripts\..\toffy\watcher_callbacks.py:295, in build_fov_callback.<locals>.fov_callback(run_folder, point_name)
    293 for arg in args:
    294     if cb := getattr(callback_obj, arg, None):
--> 295         cb(**kwargs)
    296     else:
    297         # unreachable...
    298         raise ValueError(
    299             f'Could not locate attribute {arg} in FovCallback object'
    300         )

File ~\Documents\toffy\scripts\..\toffy\watcher_callbacks.py:194, in FovCallbacks.generate_qc(self, qc_out_dir, panel, **kwargs)
    192     if panel is None:
    193         raise ValueError('Must provide panel if fov data is not already generated...')
--> 194     self._generate_fov_data(panel, **kwargs)
    196 metric_data = compute_qc_metrics_direct(
    197     image_data=self.__fov_data,
    198     fov_name=self.point_name,
    199     gaussian_blur=kwargs.get('gaussian_blur', False),
    200     blur_factor=kwargs.get('blur_factor', 1)
    201 )
    203 for metric_name, data in metric_data.items():

File ~\Documents\toffy\scripts\..\toffy\watcher_callbacks.py:128, in FovCallbacks._generate_fov_data(self, panel, intensities, replace, time_res, **kwargs)
    110 def _generate_fov_data(self, panel: pd.DataFrame, intensities=['Au', 'chan_39'], replace=True,
    111                        time_res=0.0005, **kwargs):
    112     """Extracts data from bin files using the given panel
    113 
    114     The data and the panel are then cached members of the FovCallbacks object
   (...)
    126             Unused kwargs for other functions
    127     """
--> 128     self.__fov_data = extract_bin_files(
    129         data_dir=self.run_folder,
    130         out_dir=None,
    131         include_fovs=[self.point_name],
    132         panel=panel,
    133         intensities=intensities,
    134         replace=replace,
    135         time_res=time_res
    136     )
    138     self.__panel = panel

File ~\miniconda3\envs\toffy_env\lib\site-packages\mibi_bin_tools\bin_files.py:373, in extract_bin_files(data_dir, out_dir, include_fovs, panel, intensities, replace, time_res)
    370     if type(intensities) is not list:
    371         intensities = list(fov['targets'])
--> 373 img_data = condense_img_data(img_data, list(fov['targets']), intensities, replace)
    375 if out_dir is not None:
    376     _write_out(
    377         img_data,
    378         out_dir,
   (...)
    381         intensities
    382     )

File ~\miniconda3\envs\toffy_env\lib\site-packages\mibi_bin_tools\bin_files.py:308, in condense_img_data(img_data, targets, intensities, replace)
    306         if target in intensities:
    307             img_data[0, :, :, j] = img_data[1, :, :, j]
--> 308     img_data = img_data[[0], :, :, :]
    310 # not extracting intensity
    311 elif not type_utils.any_true(intensities):

MemoryError: Unable to allocate 736. MiB for an array with shape (1, 2048, 2048, 46) and data type uint32
```

### LINKED ISSUE #348: Remove duplicate plots in notebook for intermediate callbacks
**Is your feature request related to a problem? Please describe.**
The watcher notebook reruns the intermediate callbacks after each FOV. These updated callbacks are used to generate a new version of the relevant plots, which are saved in the plotting directory. However, in the notebook, the output is appended to the previous outputs

**Describe the solution you'd like**
Either have the plot output directly replace the previous plot, or the clear the output. Right now there are 10s of different plots, each one showing the QC metrics slowly incrementing each additional FOV, rather than the single most up to date QC metric plot. Same for MPH.

### PR DESCRIPTION
**Pull request by alex-l-kong**
**What is the purpose of this PR?**

Closes #348, closes #347. To prevent plots from displaying one after each other, they need to be refreshed during the loop.

`matplotlib` does have issues with memory leaks when too many plots are opened at once, so this could also address the memory leak issue.

**How did you implement your changes**

In `watcher_callbacks`, we need to return the actual values that get generated in the intermediate callback since they may be plots.

Then, in `fov_watcher`, we need to verify that the plotting functions that could be contained in `self.inter_return_vals` (`plot_qc_metrics` and `plot_mph_metrics`) get their plots cleared.

**Remaining issues**

Testing

### CODE REVIEW

**Review by srivarra — APPROVED** [review]
Looks good, hopefully patches the leaky plots. Just one stylistic comment.

**Comment by camisowers** [comment]
Looks good!

**Review by srivarra — CHANGES_REQUESTED** [review]
Looks good, just a stylistic adjustment.

**Comment by alex-l-kong** [comment]
@ngreenwald we have to turn off interactive plotting in Jupyter to completely fix the memory issue, this is a known issue with `matplotlib` drawing multiple figures that don't get immediately shown. The QC metric saving happens in real time, however it won't actually display on the Jupyter terminal.

**Review by srivarra — APPROVED** [review]
LGTM!

**Review by ngreenwald — APPROVED** [review]
Nice, lets see if this solves it

**Pull request merged**
