### PR TITLE
Added conda-forge channel to `environment.yml`

### LINKED ISSUE #353: conda environment fails to build
*Please refer to our [FAQ](https://ark-analysis.readthedocs.io/en/latest/_rtd/faq.html) and look at our [known issues](https://github.com/angelolab/ark-analysis/issues) before opening a bug report.*

**Describe the bug**
conda environment fails to fully build upon initial setup. Specifically, the `jupyter_contrib_nbextensions` package is not found and fails upon environment build. System is Mac (Intel)

**Expected behavior**
Expected toffy_env to build successfully. 

**To Reproduce**
Please either copy/paste or screenshot all of the code you ran which produced the error. In addition, copy the full error message. 
Screenshot 2023-04-11 at 4 10 30 PM

### PR DESCRIPTION
**Pull request by srivarra**
**If you haven't already, please read through our [contributing guidelines](https://ark-analysis.readthedocs.io/en/latest/_rtd/contributing.html) before opening your PR**

**What is the purpose of this PR?**

Closes #353.

**How did you implement your changes**

Adds `conda-forge` to the `channels` section in the `environment.yml` file.

**Remaining issues**

Check if installation works properly on user devices:
- [x] Apple Silicon Mac
- [x] Intel Mac
- [x] Windows
- [x] Windows WSL2

### CODE REVIEW

**Comment by camisowers** [comment]
Looks good! We should probably have someone re-install the environment as a test.

**Comment by srivarra** [comment]
@camisowers I think an Intel mac is left.

**Comment by bryjcannon** [comment]
I'll test now on Intel mac and get back to you

**Comment by bryjcannon** [comment]
Re-installed toffy and successfully created the environment on Intel Mac! Thanks :)

**Review by camisowers — APPROVED** [review]
All good then. Thanks Bryan!

**Pull request merged**
